Repository oh-my-guide/OMG_project, pull requests merged in 2024-08, with the labels that each got.

#8 초기 설정 완료
  Weekly_Log/[1주차] idea_4팀_진행상황_공유.md
  createTable.sql
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/entity/ChatMessage.java
  src/main/java/com/example/omg_project/domain/chat/entity/ChatRoom.java
  src/main/java/com/example/omg_project/domain/chat/repository/ChatRepository.java
  src/main/java/com/example/omg_project/domain/chat/service/ChatService.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostController.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPost.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostComment.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostLike.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostReply.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostController.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/PlaceReview.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPost.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostComment.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostLike.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostReply.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/Wishlist.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostServiceImpl.java
  src/main/java/com/example/omg_project/domain/role/entity/Role.java
  src/main/java/com/example/omg_project/domain/trip/controller/TripController.java
  src/main/java/com/example/omg_project/domain/trip/entity/City.java
  src/main/java/com/example/omg_project/domain/trip/entity/Team.java
  src/main/java/com/example/omg_project/domain/trip/entity/Trip.java
  src/main/java/com/example/omg_project/domain/trip/entity/TripDate.java
  src/main/java/com/example/omg_project/domain/trip/entity/TripLocation.java
  src/main/java/com/example/omg_project/domain/trip/repository/repositoryRepository.java
  src/main/java/com/example/omg_project/domain/trip/service/TripService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripServiceImpl.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/entity/User.java
  src/main/java/com/example/omg_project/domain/user/repository/UserRepository.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/util/JwtTokenizer.java
  src/test/java/com/example/omg_project/OmgProjectApplicationTests.java
Labels: feature, priority:high, PR/ready for review

#9 [#3] 회원가입 구현
  .gitignore
  build.gradle
  src/main/java/com/example/omg_project/domain/certification/controller/MailController.java
  src/main/java/com/example/omg_project/domain/certification/entity/MailRequest.java
  src/main/java/com/example/omg_project/domain/certification/entity/VerificationRequest.java
  src/main/java/com/example/omg_project/domain/certification/service/MailService.java
  src/main/java/com/example/omg_project/domain/role/repository/RoleRepository.java
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/dto/UserSignUpDto.java
  src/main/java/com/example/omg_project/domain/user/entity/User.java
  src/main/java/com/example/omg_project/domain/user/repository/UserRepository.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/security/CustomUserDetails.java
  src/main/java/com/example/omg_project/global/security/CustomUserDetailsService.java
  src/main/resources/static/css/signup.css
  src/main/resources/templates/main/loginform.html
  src/main/resources/templates/main/signupform.html
  src/main/resources/templates/user/home.html
  src/main/resources/templates/user/mypage.html
Labels: feature, priority:high, PR/ready for review

#11 [#4] 채팅기능 구현
  build.gradle
  src/main/java/com/example/omg_project/domain/chat/config/KafkaConsumerConfig.java
  src/main/java/com/example/omg_project/domain/chat/config/KafkaProducerConfig.java
  src/main/java/com/example/omg_project/domain/chat/config/WebSocketConfig.java
  src/main/java/com/example/omg_project/domain/chat/controller/ChatApiController.java
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/dto/ChatMessageDTO.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageListener.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageProducer.java
  src/main/java/com/example/omg_project/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/example/omg_project/domain/chat/repository/ChatRepository.java
  src/main/java/com/example/omg_project/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/omg_project/domain/chat/service/ChatService.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/omg_project/domain/chat/websocket/CustomHandshakeInterceptor.java
  src/main/java/com/example/omg_project/domain/chat/websocket/WebSocketHandler.java
  src/main/java/com/example/omg_project/domain/user/repository/UserRepository.java
  src/main/resources/templates/chat/chat.html
Labels: feature, priority:high, PR/ready for review

#12 [#10] JWT 로그인 기능
  .gitignore
  src/main/java/com/example/omg_project/domain/certification/controller/MailApiController.java
  src/main/java/com/example/omg_project/domain/certification/entity/MailRequest.java
  src/main/java/com/example/omg_project/domain/certification/entity/VerificationRequest.java
  src/main/java/com/example/omg_project/domain/certification/service/MailService.java
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/dto/UserLoginDto.java
  src/main/java/com/example/omg_project/domain/user/dto/UserLoginResponseDto.java
  src/main/java/com/example/omg_project/domain/user/repository/UserRepository.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/entity/JwtBlacklist.java
  src/main/java/com/example/omg_project/global/jwt/entity/RefreshToken.java
  src/main/java/com/example/omg_project/global/jwt/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/omg_project/global/jwt/exception/JwtExceptionCode.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
  src/main/java/com/example/omg_project/global/jwt/repository/JwtBlacklistRepository.java
  src/main/java/com/example/omg_project/global/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/example/omg_project/global/jwt/service/JwtBlacklistService.java
  src/main/java/com/example/omg_project/global/jwt/service/RefreshTokenService.java
  src/main/java/com/example/omg_project/global/jwt/token/JwtAuthenticationToken.java
  src/main/java/com/example/omg_project/global/jwt/util/JwtTokenizer.java
  src/main/java/com/example/omg_project/global/security/CustomUserDetails.java
  src/main/resources/static/js/signup.js
  src/main/resources/templates/main/loginform.html
  src/main/resources/templates/main/signupform.html
  src/main/resources/templates/user/home.html
  src/main/resources/templates/user/mypage.html
  src/test/java/com/example/omg_project/test.http
Labels: feature, priority:high, PR/ready for review

#15 [#14] OAuth2 로그인 구현
  build.gradle
  src/main/java/com/example/omg_project/domain/role/entity/Role.java
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/dto/UserEditDto.java
  src/main/java/com/example/omg_project/domain/user/entity/User.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/entity/JwtBlacklist.java
  src/main/java/com/example/omg_project/global/jwt/entity/RefreshToken.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
  src/main/java/com/example/omg_project/global/jwt/util/JwtTokenizer.java
  src/main/java/com/example/omg_project/global/oauth2/dto/CustomOAuth2User.java
  src/main/java/com/example/omg_project/global/oauth2/dto/GoogleResponse.java
  src/main/java/com/example/omg_project/global/oauth2/dto/KakaoResponse.java
  src/main/java/com/example/omg_project/global/oauth2/dto/NaverResponse.java
  src/main/java/com/example/omg_project/global/oauth2/dto/OAuth2Response.java
  src/main/java/com/example/omg_project/global/oauth2/handle/CustomSuccessHandler.java
  src/main/java/com/example/omg_project/global/oauth2/service/CustomOauth2UserService.java
  src/main/resources/static/css/mypage-Edit.css
  src/main/resources/static/js/mypage-Edit.js
  src/main/resources/templates/main/loginform.html
  src/main/resources/templates/main/signupform.html
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/user/mypageEdit.html
  src/main/resources/templates/user/oauthPage.html
Labels: feature, refactor, priority:high, PR/ready for review

#16 [#3] 자동 닉네임 생성
  src/main/java/com/example/omg_project/domain/user/controller/UserApiController.java
  src/main/java/com/example/omg_project/domain/user/entity/RandomNickname.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
  src/main/resources/static/js/mypage-Edit.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/main/signupform.html
  src/main/resources/templates/user/mypageEdit.html
  src/main/resources/templates/user/oauthPage.html
Labels: feature, enhancement, PR/ready for review

#18 [#7] 카카오맵 API 기능 구현
  build.gradle
  src/main/java/com/example/omg_project/domain/trip/controller/MapApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/MapViewController.java
  src/main/java/com/example/omg_project/domain/trip/dto/TripLocationDto.java
  src/main/java/com/example/omg_project/domain/trip/repository/TripLocationRepository.java
  src/main/java/com/example/omg_project/domain/trip/service/TripLocationService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripLocationServiceImpl.java
  src/main/resources/templates/map/map.html
Labels: feature, priority:high, PR/ready for review

#19 [#5] 일행 모집 게시판 기능 구현
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostApiController.java
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostCommentApiController.java
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostController.java
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostLikeApiController.java
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostReplyApiController.java
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostCommentDto.java
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostDto.java
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostReplyDto.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPost.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostComment.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostLike.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostReply.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostCommentRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostLikeRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostReplyRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostCommentService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostLikeService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostReplyService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostCommentServiceImpl.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostLikeServiceImpl.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostReplyServiceImpl.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostServiceImpl.java
  src/main/resources/templates/join/createpost.html
  src/main/resources/templates/join/listposts.html
  src/main/resources/templates/join/updatepost.html
  src/main/resources/templates/join/viewpost.html
Labels: feature, priority:high, PR/ready for review

#20 [#17] 후기 게시판 기능 구현
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostApiController.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostCommentApiController.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostController.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostLikeApiController.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostReplyApiController.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostCommentDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostReplyDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/PlaceReview.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPost.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostComment.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostLike.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostReply.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/Wishlist.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/PlaceReviewRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostCommentRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostLikeRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostReplyRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/WishlistRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/PlaceReviewService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostCommentService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostLikeService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostReplyService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/WishlistService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/PlaceReviewServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostCommentServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostLikeServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostReplyServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/WishlistServiceImpl.java
  src/main/resources/templates/review/createpost.html
  src/main/resources/templates/review/listposts.html
  src/main/resources/templates/review/updatepost.html
  src/main/resources/templates/review/viewpost.html
Labels: feature, priority:high, PR/ready for review

#27 [#13] jwt인증 기반 사용자 채팅 인가 구현
  src/main/java/com/example/omg_project/domain/chat/controller/ChatApiController.java
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/service/ChatService.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/omg_project/domain/chat/websocket/CustomHandshakeInterceptor.java
  src/main/java/com/example/omg_project/domain/chat/websocket/WebSocketHandler.java
  src/main/java/com/example/omg_project/domain/trip/repository/TeamRepository.java
  src/main/java/com/example/omg_project/domain/trip/service/TeamService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/user/home.html
Labels: feature, enhancement, priority:high, PR/in review

#33 [#24] 비밀번호 찾기 및 회원 탈퇴 기능 구현
  src/main/java/com/example/omg_project/domain/certification/controller/MailApiController.java
  src/main/java/com/example/omg_project/domain/certification/service/MailService.java
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/domain/user/controller/MailApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/dto/request/MailRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/request/MailVerificationRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/request/PasswordVerificationRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/request/UserEditDto.java
  src/main/java/com/example/omg_project/domain/user/dto/request/UserLoginDto.java
  src/main/java/com/example/omg_project/domain/user/dto/request/UserSignUpDto.java
  src/main/java/com/example/omg_project/domain/user/dto/response/UserLoginResponseDto.java
  src/main/java/com/example/omg_project/domain/user/repository/UserRepository.java
  src/main/java/com/example/omg_project/domain/user/service/MailService.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/MailServiceImpl.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/DataInitializer.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
  src/main/java/com/example/omg_project/global/jwt/util/JwtTokenizer.java
  src/main/resources/static/css/loginform.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/files/google.png
  src/main/resources/static/files/kakao.png
  src/main/resources/static/files/naver.png
  src/main/resources/static/js/mypage-Edit.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/main/loginform.html
  src/main/resources/templates/main/signupform.html
  src/main/resources/templates/user/findPassword.html
  src/main/resources/templates/user/mypage.html
Labels: feature, enhancement, PR/ready for review

#34 [#25] 일행 모집 게시글 작성 시 관련된 여행 일정 보여주기
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostApiController.java
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostController.java
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostCommentDto.java
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostDto.java
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostReplyDto.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPost.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostComment.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostReply.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostServiceImpl.java
  src/main/resources/templates/join/createpost.html
  src/main/resources/templates/join/listposts.html
  src/main/resources/templates/join/updatepost.html
  src/main/resources/templates/join/viewpost.html
Labels: enhancement, priority:high, PR/ready for review

#36 [#32] 초대코드로 팀 추가/탈퇴 기능 구현
  src/main/java/com/example/omg_project/domain/trip/controller/TeamApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TeamController.java
  src/main/java/com/example/omg_project/domain/trip/repository/TeamRepository.java
  src/main/java/com/example/omg_project/domain/trip/repository/TripRepository.java
  src/main/java/com/example/omg_project/domain/trip/service/TeamService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/resources/templates/team/join.html
  src/main/resources/templates/team/myteam.html
Labels: feature, backend, PR/ready for review

#37 [#26] 후기 게시글 작성 시 여행 선택하여 등록하기
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostApiController.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostController.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostCommentDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostReplyDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPost.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostComment.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostReply.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostServiceImpl.java
  src/main/resources/templates/review/createpost.html
  src/main/resources/templates/review/listposts.html
  src/main/resources/templates/review/updatepost.html
  src/main/resources/templates/review/viewpost.html
Labels: enhancement, priority:high, PR/ready for review

#38 fix: team 충돌 해결
  src/main/java/com/example/omg_project/domain/trip/repository/TeamRepository.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
Labels: bug, priority:high, PR/ready for review

#40 [#22] 여행 일정 생성 및 수정 시 카카오 지도 API 연동하기 구현
  src/main/java/com/example/omg_project/domain/trip/controller/MapApiController.java
  src/main/java/com/example/omg_project/domain/trip/dto/TripLocationDTO.java
  src/main/java/com/example/omg_project/domain/trip/dto/TripLocationDto.java
  src/main/java/com/example/omg_project/domain/trip/service/TripLocationService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripLocationServiceImpl.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripServiceImpl.java
  src/main/resources/static/css/map.css
  src/main/resources/static/css/trip.css
  src/main/resources/static/js/map.js
  src/main/resources/templates/map/map.html
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: feature, priority:high, PR/ready for review

#46 [#45][#51] 일정 상세조회, 초대코드 입력, 팀 목록 페이지 css, js 수정 & leader일 경우 초대코드 보이게 구현
  src/main/java/com/example/omg_project/domain/trip/controller/TripApiController.java
  src/main/java/com/example/omg_project/domain/trip/service/TeamService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/resources/templates/team/join.html
  src/main/resources/templates/team/myteam.html
  src/main/resources/templates/trip/viewtripdetails.html
Labels: enhancement, refactor, priority:medium, PR/ready for review

#50 [#49] 게시판 css 수정
  src/main/resources/templates/join/createpost.html
  src/main/resources/templates/join/listposts.html
  src/main/resources/templates/join/updatepost.html
  src/main/resources/templates/join/viewpost.html
  src/main/resources/templates/review/createpost.html
  src/main/resources/templates/review/listposts.html
  src/main/resources/templates/review/updatepost.html
  src/main/resources/templates/review/viewpost.html
Labels: refactor, priority:medium, PR/ready for review

#48 [#42][#44] 여행 일정 생성, 수정 디자인 & 수정 시 새로고침 버그 해결
  src/main/java/com/example/omg_project/domain/trip/controller/MapApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/MapViewController.java
  src/main/java/com/example/omg_project/domain/trip/dto/TripLocationDTO.java
  src/main/java/com/example/omg_project/domain/trip/service/TripLocationService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripLocationServiceImpl.java
  src/main/resources/static/css/map.css
  src/main/resources/static/css/trip.css
  src/main/resources/static/js/map.js
  src/main/resources/templates/map/map.html
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: feature, bug, refactor, priority:medium, PR/ready for review

#54 [#52] 홈화면 및 채팅방 디자인
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/service/ChatService.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/omg_project/domain/trip/controller/EventApiController.java
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/user/home.html
Labels: feature, enhancement, priority:medium, PR/ready for review

#55 fix: 마이페이지 코드 수정
  src/main/resources/templates/user/mypage.html
Labels: enhancement

#57 fix: 여행 상세조회 css 수정
  src/main/resources/templates/trip/viewtripdetails.html
Labels: enhancement, priority:medium, frontend

#60 [#56] 여행 일정 생성 방식 선택 구현
  src/main/java/com/example/omg_project/domain/trip/controller/TripController.java
  src/main/resources/templates/trip/createorjoin.html
  src/main/resources/templates/user/home.html
Labels: enhancement, priority:medium, PR/in review

#61 [#59] 사용자 마이페이지 기능 구현
  src/main/java/com/example/omg_project/domain/user/controller/AdminController.java
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/domain/user/controller/MailApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/resources/templates/user/admin-all-user.html
  src/main/resources/templates/user/mypage.html
Labels: enhancement, frontend, backend, PR/ready for review

#62 refactor: 쿠키에서 accessToken 받아오는 로직 메서드화
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/global/jwt/util/JwtTokenizer.java
Labels: enhancement, priority:high, PR/ready for review

#64 [#63] 조회 username 비교 부분 jwt 토큰 파싱으로 변경, 컨트롤러에 user 객체 담기
  src/main/java/com/example/omg_project/domain/trip/controller/TeamController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TripController.java
Labels: enhancement, backend, PR/ready for review

#65 [#58] 찜하기 기능 구현
  src/main/java/com/example/omg_project/domain/reviewpost/controller/WishlistApiController.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/WishlistDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/WishlistRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/WishlistService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/WishlistServiceImpl.java
  src/main/resources/templates/review/viewpost.html
Labels: feature, priority:low, PR/ready for review

#68 [#67] 페이지 공통 header 작성
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/global/jwt/util/JwtTokenizer.java
  src/main/resources/static/css/header.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/user/home.html
Labels: feature, priority:high, PR/in review

#71 [#59] jwt 토큰 파싱 변경
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
Labels: enhancement, backend, PR/ready for review

#74 폼 헤더 추가
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/resources/static/css/mypage-Edit.css
  src/main/resources/static/css/mypage.css
  src/main/resources/templates/main/service.html
  src/main/resources/templates/user/admin-all-user.html
  src/main/resources/templates/user/findPassword.html
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/user/mypageEdit.html
  src/main/resources/templates/user/oauth2page.html
Labels: enhancement, frontend, backend, PR/ready for review

#73 style: 여행 일정 조회/초대코드 입력/팀 목록 조회 페이지 헤더 추가
  src/main/resources/templates/team/join.html
  src/main/resources/templates/team/myteam.html
  src/main/resources/templates/trip/viewtripdetails.html
Labels: enhancement, priority:medium, frontend

#75 [#49] 헤더 추가
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostController.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostController.java
  src/main/resources/templates/join/createpost.html
  src/main/resources/templates/join/listposts.html
  src/main/resources/templates/join/updatepost.html
  src/main/resources/templates/join/viewpost.html
  src/main/resources/templates/review/createpost.html
  src/main/resources/templates/review/listposts.html
  src/main/resources/templates/review/updatepost.html
  src/main/resources/templates/review/viewpost.html
Labels: enhancement, priority:high, PR/ready for review

#77 [#76] 댓글의 작성자가 비밀 대댓글 조회하지 못하는 버그 해결
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostReplyDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostReplyDto.java
  src/main/resources/templates/join/viewpost.html
  src/main/resources/templates/review/viewpost.html
Labels: bug, priority:high, PR/ready for review

#79 style: 헤더와 홈화면 디자인 수정 및 로고 추가
  src/main/resources/static/css/header.css
  src/main/resources/static/images/omgLogo.jpg
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/user/home.html
Labels: feature, enhancement, priority:medium, PR/in review

#81 style: 팀 목록 페이지로 넘어가는 버튼 생성
  src/main/resources/static/css/mypage.css
  src/main/resources/templates/user/mypage.html
Labels: enhancement, priority:medium, frontend, PR/ready for review

#82 채팅방 이동 버튼 생성
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/trip/service/TeamService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/resources/static/css/header.css
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/team/myteam.html
Labels: feature, enhancement, priority:high, PR/approved

#83 여행 일정과 장소 인덱스, 지도 마커 표시, 선택 갯수 제한 구현
  src/main/resources/static/css/map.css
  src/main/resources/static/css/trip.css
  src/main/resources/static/js/createtrip.js
  src/main/resources/static/js/updatetrip.js
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: feature, enhancement, priority:high, PR/ready for review

#87 [#85] 초대코드 잘못 입력 시 맞는 얼럿창 띄우기
  src/main/java/com/example/omg_project/domain/trip/controller/TeamApiController.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/resources/templates/team/join.html
Labels: enhancement, bug, PR/ready for review

#86 docs Readme 업로드
  README.md
  Weekly_Log/[2주차] idea_4팀_진행사항_공유.md
  Weekly_Log/[3주차] idea_4팀_진행사항_공유.md
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
Labels: documentation

#88 채팅 가능하게 수정
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageProducer.java
Labels: enhancement, priority:high, PR/in review

#90 [#29] 채팅방 생성시 바로 채팅이 가능하도록 수정
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageListener.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageProducer.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/resources/templates/team/myteam.html
Labels: enhancement, bug, priority:high, PR/in review

#89 rename: 로고 파일 위치 변경
  src/main/resources/static/files/omgLogo.jpg
  src/main/resources/templates/fragments/header.html
Labels: enhancement, PR/ready for review

#96 [#72][#80] 일정 수정 시 마커 제거 오류 수정 & 날짜별 마커 색상 구분 기능 추가
  src/main/resources/static/files/markers/marker_number_blue.png
  src/main/resources/static/files/markers/marker_number_cyan.png
  src/main/resources/static/files/markers/marker_number_green.png
  src/main/resources/static/files/markers/marker_number_purple.png
  src/main/resources/static/files/markers/marker_number_red.png
  src/main/resources/static/files/markers/marker_number_yellow.png
  src/main/resources/static/js/createtrip.js
  src/main/resources/static/js/updatetrip.js
  src/main/resources/templates/trip/updatetrip.html
Labels: feature, priority:high, PR/ready for review, bugfix

#95 [#94] 비밀번호 재설정 로직
  build.gradle
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/domain/user/controller/MailApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/dto/request/Oauth2LoginRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/request/UserEditRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/request/UserLoginRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/request/UserPasswordChangeRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/request/UserSignUpRequest.java
  src/main/java/com/example/omg_project/domain/user/dto/response/UserLoginResponse.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
  src/main/java/com/example/omg_project/global/oauth2/handle/CustomSuccessHandler.java
  src/main/java/com/example/omg_project/global/oauth2/service/CustomOauth2UserService.java
  src/main/resources/static/js/myedit.js
  src/main/resources/static/js/mypage-Edit.js
  src/main/resources/static/js/oauth2-page-add.js
  src/main/resources/templates/main/loginform.html
  src/main/resources/templates/user/change-Password.html
  src/main/resources/templates/user/findPassword.html
  src/main/resources/templates/user/mypageEdit.html
  src/main/resources/templates/user/oauth2page.html
Labels: feature, refactor, backend, PR/ready for review

#101 [#97] 일정 날짜 수정 및 내 일정으로 가져오기 기능 구현
  src/main/java/com/example/omg_project/domain/trip/controller/TripApiController.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripServiceImpl.java
  src/main/resources/templates/review/viewpost.html
  src/main/resources/templates/team/join.html
  src/main/resources/templates/team/myteam.html
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: enhancement, priority:high, PR/ready for review

#103 [#102] 지도에 장소 경로를 선으로 이어 나타내도록 구현
  src/main/resources/static/js/createtrip.js
  src/main/resources/static/js/updatetrip.js
  src/main/resources/templates/trip/updatetrip.html
Labels: feature, priority:high, PR/ready for review

#99 [#93] 채팅시 비속어 필터링 기능 추가
  src/main/java/com/example/omg_project/domain/chat/controller/ChatApiController.java
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/entity/BadWord.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageListener.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageProducer.java
  src/main/java/com/example/omg_project/domain/chat/repository/BadWordRepository.java
  src/main/java/com/example/omg_project/domain/chat/service/BadWordService.java
  src/main/java/com/example/omg_project/domain/chat/service/ChatService.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/BadWordServiceImpl.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/ChatServiceImpl.java
  src/main/resources/templates/chat/chat.html
Labels: feature, enhancement, priority:medium, PR/ready for review

#109 [#104] 날짜 수정 시 day가 끊임없이 늘어나는 문제와 사라지는 세부장소의 문제 해결
  src/main/java/com/example/omg_project/domain/trip/repository/TeamRepository.java
  src/main/resources/templates/trip/updatetrip.html
Labels: enhancement, question, frontend, PR/ready for review

#110 fix: User 상태 추가 + 회원 탈퇴
  src/main/java/com/example/omg_project/domain/user/entity/User.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/oauth2/service/CustomOauth2UserService.java
Labels: bug, question, PR/awaiting changes

#114 [#110] 회원 탈퇴 시 채팅 메시지, 댓글, 대댓글 삭제안되는 문제 해결
  src/main/java/com/example/omg_project/domain/chat/entity/ChatRoom.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPostComment.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostCommentRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostReplyRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostCommentService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostReplyService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostCommentServiceImpl.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostReplyServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPostComment.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostCommentRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostReplyRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostCommentService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostReplyService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostCommentServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostReplyServiceImpl.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
Labels: feature, priority:high, PR/ready for review, bugfix

#116 [#113] 일정 생성 페이지에 여행 명소 추천 기능 추가
  src/main/java/com/example/omg_project/domain/trip/controller/CityApiController.java
  src/main/java/com/example/omg_project/domain/trip/createCity.sql
  src/main/java/com/example/omg_project/domain/trip/service/CityService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/CityServiceImpl.java
  src/main/resources/static/css/recommend.css
  src/main/resources/templates/trip/createtrip.html
Labels: feature, frontend, PR/ready for review

#115 [#112] 관리자 페이지 구현 및 코드 리팩토링
  src/main/java/com/example/omg_project/domain/user/controller/AdminController.java
  src/main/java/com/example/omg_project/domain/user/controller/AuthController.java
  src/main/java/com/example/omg_project/domain/user/controller/MailApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/service/impl/MailServiceImpl.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/RedisConfig.java
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
  src/main/resources/static/js/myedit.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/main/faq.html
  src/main/resources/templates/user/admin-all-review.html
  src/main/resources/templates/user/admin-all-user.html
  src/main/resources/templates/user/change-Password.html
  src/main/resources/templates/user/mypageEdit.html
Labels: feature, backend, PR/ready for review

#117 [#105] 사용자 프로필 사진 등록 + S3 업로드 구현
  build.gradle
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/service/UserService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/omg_project/global/config/S3Config.java
  src/main/java/com/example/omg_project/global/exception/CustomException.java
  src/main/java/com/example/omg_project/global/exception/ErrorCode.java
  src/main/java/com/example/omg_project/global/image/service/ImageService.java
  src/main/java/com/example/omg_project/global/image/service/impl/ImageServiceImpl.java
  src/main/resources/templates/user/mypage.html
  src/main/resources/templates/user/mypageEdit.html
Labels: feature, priority:high, PR/ready for review

#118 [#108] 게시판 고도화 1차 풀리퀘
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostApiController.java
  src/main/java/com/example/omg_project/domain/joinpost/controller/JoinPostController.java
  src/main/java/com/example/omg_project/domain/joinpost/dto/JoinPostDto.java
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPost.java
  src/main/java/com/example/omg_project/domain/joinpost/repository/JoinPostRepository.java
  src/main/java/com/example/omg_project/domain/joinpost/service/JoinPostService.java
  src/main/java/com/example/omg_project/domain/joinpost/service/impl/JoinPostServiceImpl.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostApiController.java
  src/main/java/com/example/omg_project/domain/reviewpost/controller/ReviewPostController.java
  src/main/java/com/example/omg_project/domain/reviewpost/dto/ReviewPostDto.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPost.java
  src/main/java/com/example/omg_project/domain/reviewpost/repository/ReviewPostRepository.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/ReviewPostService.java
  src/main/java/com/example/omg_project/domain/reviewpost/service/impl/ReviewPostServiceImpl.java
  src/main/resources/templates/join/createpost.html
  src/main/resources/templates/join/listposts.html
  src/main/resources/templates/join/updatepost.html
  src/main/resources/templates/join/viewpost.html
  src/main/resources/templates/review/listposts.html
  src/main/resources/templates/review/viewpost.html
Labels: feature, priority:high, PR/ready for review

#119 [#112] 고도화 기능 구현
  build.gradle
  src/main/java/com/example/omg_project/domain/trip/controller/EventApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/controller/WeatherApiController.java
  src/main/java/com/example/omg_project/domain/user/service/impl/MailServiceImpl.java
  src/main/java/com/example/omg_project/global/config/RestTemplateConfig.java
  src/main/resources/templates/main/loginform.html
  src/main/resources/templates/user/home.html
Labels: feature, backend, PR/ready for review

#121 [#120] UserController의 updateUserProfile() 리팩토링 후 프로필 이미지 기능 동작 오류 수정
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/resources/templates/user/mypageEdit.html
Labels: priority:high, PR/ready for review, bugfix

#124 [#123] 채팅 이미지 기능 추가
  src/main/java/com/example/omg_project/domain/chat/controller/ChatApiController.java
  src/main/resources/templates/chat/chat.html
Labels: feature, priority:medium, PR/ready for review

#126 [#111] CKEditor 이미지 업로드 구현 & joinPost, reviewPost 테이블 데이터 타입 수정
  src/main/java/com/example/omg_project/domain/joinpost/entity/JoinPost.java
  src/main/java/com/example/omg_project/domain/reviewpost/entity/ReviewPost.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/global/image/controller/ImageController.java
  src/main/java/com/example/omg_project/global/image/service/ImageService.java
  src/main/java/com/example/omg_project/global/image/service/impl/ImageServiceImpl.java
Labels: feature, refactor, priority:high, database, PR/ready for review

#127 [#113] 여행 명소 추천 기능 수정 페이지에 추가, 최신 정렬
  src/main/java/com/example/omg_project/domain/trip/controller/CityApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TripApiController.java
  src/main/java/com/example/omg_project/domain/trip/repository/TripRepository.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripServiceImpl.java
  src/main/resources/static/css/recommend.css
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: feature, frontend, PR/ready for review

#129 [#128] 명소 추천 키워드 검색 -> 도시 위치 기반 검색으로 변경
  src/main/java/com/example/omg_project/domain/trip/controller/TourApiController.java
  src/main/java/com/example/omg_project/domain/trip/repository/TripLocationRepository.java
  src/main/java/com/example/omg_project/domain/trip/repository/TripRepository.java
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: enhancement, priority:medium, frontend, PR/ready for review

#130 [#112] 관리자 - 고도화 기능 구현
  src/main/java/com/example/omg_project/domain/user/controller/AdminController.java
  src/main/java/com/example/omg_project/domain/user/entity/AdminNotice.java
  src/main/java/com/example/omg_project/domain/user/entity/User.java
  src/main/java/com/example/omg_project/domain/user/repository/AdminNoticeRepository.java
  src/main/java/com/example/omg_project/domain/user/service/AdminNoticeService.java
  src/main/java/com/example/omg_project/domain/user/service/impl/AdminNoticeServiceImpl.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/main/faq.html
  src/main/resources/templates/user/admin-all-review.html
  src/main/resources/templates/user/admin-all-user.html
  src/main/resources/templates/user/admin-notice-view.html
  src/main/resources/templates/user/admin-notice.html
  src/main/resources/templates/user/admin-noticeDetail.html
Labels: feature, backend, PR/ready for review

#133 refactor: 내 일정으로 담기 버튼 찜 부분으로 이동, 예외처리 추가
  src/main/java/com/example/omg_project/domain/trip/controller/TeamApiController.java
  src/main/java/com/example/omg_project/domain/trip/repository/TeamRepository.java
  src/main/java/com/example/omg_project/domain/trip/service/TeamService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/resources/templates/team/join.html
  src/main/resources/templates/team/myteam.html
  src/main/resources/templates/trip/updatetrip.html
  src/main/resources/templates/user/mypage.html
Labels: enhancement, priority:low, frontend, PR/ready for review

#135 fix: 내 일정으로 담기 오류 수정
  src/main/java/com/example/omg_project/domain/reviewpost/dto/WishlistDto.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripServiceImpl.java
  src/main/java/com/example/omg_project/global/config/JacksonConfig.java
  src/main/java/com/example/omg_project/global/exception/ErrorCode.java
  src/main/resources/templates/team/myteam.html
  src/main/resources/templates/trip/updatetrip.html
  src/main/resources/templates/trip/viewtripdetails.html
  src/main/resources/templates/user/mypage.html
Labels: frontend, PR/ready for review, bugfix

#136 공통예외처리 및 알림기능 주석 추가
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageListener.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/ChatServiceImpl.java
  src/main/java/com/example/omg_project/domain/notification/controller/NotificationApiController.java
  src/main/java/com/example/omg_project/domain/notification/controller/NotificationController.java
  src/main/java/com/example/omg_project/domain/notification/service/impl/NotificationImpl.java
  src/main/java/com/example/omg_project/domain/notification/service/redis/NotificationSubscriber.java
  src/main/java/com/example/omg_project/global/exception/ErrorCode.java
  src/main/resources/templates/notification/notification.html
Labels: enhancement, backend, PR/ready for review

#142 refactor: 일정 생성 후 화면 리디렉션, 일정 조회 화면 수정
  src/main/java/com/example/omg_project/domain/trip/controller/TripApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TripController.java
  src/main/java/com/example/omg_project/domain/trip/dto/CreateTripDTO.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripServiceImpl.java
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/viewtripdetails.html
Labels: enhancement, frontend, backend, PR/ready for review

#145 알림 시간 제대로 보이도록 수정
  src/main/resources/templates/notification/notification.html
Labels: enhancement, priority:high, PR/ready for review
