Repository oh-my-guide/OMG_project, pull requests merged in 2024-09, with the labels that each got.

#147 refactor: css 수정 및 캘린더 문제 해결
  src/main/java/com/example/omg_project/domain/trip/controller/EventApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/MailApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserApiController.java
  src/main/java/com/example/omg_project/domain/user/controller/UserController.java
  src/main/java/com/example/omg_project/domain/user/controller/WeatherApiController.java
  src/main/java/com/example/omg_project/global/exception/ErrorCode.java
  src/main/java/com/example/omg_project/global/oauth2/handle/CustomSuccessHandler.java
  src/main/java/com/example/omg_project/global/oauth2/service/CustomOauth2UserService.java
  src/main/resources/static/css/find-password.css
  src/main/resources/static/css/oauth2-page.css
  src/main/resources/static/js/oauth2-page-add.js
  src/main/resources/templates/main/signupform.html
  src/main/resources/templates/user/change-Password.html
  src/main/resources/templates/user/findPassword.html
  src/main/resources/templates/user/home.html
  src/main/resources/templates/user/oauth2page.html
Labels: refactor, frontend

#148 [#146][#149] 여행 일정 생성/수정 페이지 - 여행 날짜 수정 시 장소 순서, 지도에 표시 알맞게 수정 & 여행 데이터 못 읽어오는 문제 해결
  build.gradle
  src/main/resources/static/js/createtrip.js
  src/main/resources/static/js/updatetrip.js
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: enhancement, priority:high, PR/ready for review, bugfix

#158 [#157] CI/CD 구현
  .github/workflows/ci.yml
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/com/example/omg_project/domain/chat/config/KafkaConsumerConfig.java
  src/main/java/com/example/omg_project/domain/chat/config/KafkaProducerConfig.java
  src/main/java/com/example/omg_project/domain/trip/controller/TripController.java
  src/main/resources/templates/chat/chat.html
  src/test/java/com/example/omg_project/OmgProjectApplicationTests.java
Labels: feature, priority:high, PR/ready for review

#160 fix: 비로그인 사용자 코드 수정
  src/main/java/com/example/omg_project/global/config/SecurityConfig.java
  src/main/java/com/example/omg_project/global/jwt/filter/JWTFilter.java
Labels: backend, bugfix

#163 doc: readme 파일 작성
  README.md
Labels: documentation

#164 readme 작성
  README.md
Labels: documentation

#166 refactor: trip, team 관련 컨트롤러, 서비스, DTO 주석 추가 & 필요 없는 임포트 삭제
  src/main/java/com/example/omg_project/domain/trip/controller/CityApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TeamApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TeamController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TourApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TripApiController.java
  src/main/java/com/example/omg_project/domain/trip/controller/TripController.java
  src/main/java/com/example/omg_project/domain/trip/dto/CityDTO.java
  src/main/java/com/example/omg_project/domain/trip/dto/CreateTripDTO.java
  src/main/java/com/example/omg_project/domain/trip/dto/ReadTripDTO.java
  src/main/java/com/example/omg_project/domain/trip/dto/UpdateTripDTO.java
  src/main/java/com/example/omg_project/domain/trip/service/CityService.java
  src/main/java/com/example/omg_project/domain/trip/service/TeamService.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/CityServiceImpl.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TeamServiceImpl.java
  src/main/java/com/example/omg_project/domain/trip/service/impl/TripServiceImpl.java
Labels: enhancement, priority:medium, backend, PR/ready for review

#169 refactor: 메서드 설명 추가 및 불필요한 코드 삭제
  src/main/java/com/example/omg_project/global/image/controller/ImageController.java
  src/main/java/com/example/omg_project/global/image/service/impl/ImageServiceImpl.java
  src/main/resources/static/js/createtrip.js
  src/main/resources/static/js/updatetrip.js
  src/main/resources/templates/trip/createtrip.html
  src/main/resources/templates/trip/updatetrip.html
Labels: refactor, priority:low, PR/ready for review

#170 채팅 이미지 전송 버그 수정 및 불필요 코드제거, 주석 추가
  src/main/java/com/example/omg_project/domain/chat/config/KafkaConsumerConfig.java
  src/main/java/com/example/omg_project/domain/chat/config/KafkaProducerConfig.java
  src/main/java/com/example/omg_project/domain/chat/controller/ChatApiController.java
  src/main/java/com/example/omg_project/domain/chat/controller/ChatController.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageListener.java
  src/main/java/com/example/omg_project/domain/chat/kafka/ChatMessageProducer.java
  src/main/java/com/example/omg_project/domain/chat/service/impl/BadWordServiceImpl.java
  src/main/java/com/example/omg_project/domain/chat/websocket/CustomHandshakeInterceptor.java
  src/main/java/com/example/omg_project/domain/chat/websocket/WebSocketHandler.java
  src/main/java/com/example/omg_project/domain/notification/controller/NotificationApiController.java
  src/main/java/com/example/omg_project/domain/notification/controller/NotificationController.java
  src/main/java/com/example/omg_project/domain/notification/service/impl/NotificationImpl.java
  src/main/java/com/example/omg_project/domain/notification/service/redis/NotificationSubscriber.java
  src/main/java/com/example/omg_project/domain/notification/websocket/NotificationWebSocketHandler.java
  src/main/resources/templates/chat/chat.html
Labels: priority:high, PR/ready for review, bugfix

#173 feat: 코드 추가
  src/main/java/com/example/omg_project/domain/trip/repository/TeamRepository.java
  src/main/java/com/example/omg_project/domain/trip/repository/TripDateRepository.java
  src/main/java/com/example/omg_project/domain/trip/repository/TripLocationRepository.java
  src/main/java/com/example/omg_project/domain/user/entity/AdminNotice.java
  src/main/java/com/example/omg_project/global/config/RedisConfig.java
Labels: backend, PR/ready for review

#175 fix: 게시판 이미지 업로드 수정
  src/main/java/com/example/omg_project/global/image/controller/ImageController.java
Labels: priority:high, PR/ready for review, bugfix

#177 Readme 수정
  README.md
  src/main/resources/static/readmeImage/img.png
  src/main/resources/static/readmeImage/img_1.png
  src/main/resources/static/readmeImage/img_10.png
  src/main/resources/static/readmeImage/img_11.png
  src/main/resources/static/readmeImage/img_12.png
  src/main/resources/static/readmeImage/img_13.png
  src/main/resources/static/readmeImage/img_14.png
  src/main/resources/static/readmeImage/img_15.png
  src/main/resources/static/readmeImage/img_16.png
  src/main/resources/static/readmeImage/img_17.png
  src/main/resources/static/readmeImage/img_18.png
  src/main/resources/static/readmeImage/img_19.png
  src/main/resources/static/readmeImage/img_2.png
  src/main/resources/static/readmeImage/img_20.png
  src/main/resources/static/readmeImage/img_21.png
  src/main/resources/static/readmeImage/img_22.png
  src/main/resources/static/readmeImage/img_3.png
  src/main/resources/static/readmeImage/img_4.png
  src/main/resources/static/readmeImage/img_5.png
  src/main/resources/static/readmeImage/img_6.png
  src/main/resources/static/readmeImage/img_7.png
  src/main/resources/static/readmeImage/img_8.png
  src/main/resources/static/readmeImage/img_9.png
Labels: documentation

#178 readme 데모 추가
  README.md
  src/main/resources/static/readmeImage/img.png
  src/main/resources/static/readmeImage/img_1.png
  src/main/resources/static/readmeImage/img_10.png
  src/main/resources/static/readmeImage/img_11.png
  src/main/resources/static/readmeImage/img_12.png
  src/main/resources/static/readmeImage/img_13.png
  src/main/resources/static/readmeImage/img_14.png
  src/main/resources/static/readmeImage/img_15.png
  src/main/resources/static/readmeImage/img_16.png
  src/main/resources/static/readmeImage/img_17.png
  src/main/resources/static/readmeImage/img_18.png
  src/main/resources/static/readmeImage/img_19.png
  src/main/resources/static/readmeImage/img_2.png
  src/main/resources/static/readmeImage/img_20.png
  src/main/resources/static/readmeImage/img_21.png
  src/main/resources/static/readmeImage/img_22.png
  src/main/resources/static/readmeImage/img_3.png
  src/main/resources/static/readmeImage/img_4.png
  src/main/resources/static/readmeImage/img_5.png
  src/main/resources/static/readmeImage/img_6.png
  src/main/resources/static/readmeImage/img_7.png
  src/main/resources/static/readmeImage/img_8.png
  src/main/resources/static/readmeImage/img_9.png
Labels: documentation

#180 docs: readme 수정 및 main에 바로 올린 내용 develop에 merge
  README.md
Labels: documentation

#181 readme merge
  README.md
Labels: documentation
